# Generated by Django 2.0.7 on 2018-07-31 08:09

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration does not do anything, but is used to set the default group
    """

    dependencies = [("promgen", "0002_auto_20180316_0525")]
