# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0003_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
