# Generated by Django 2.0.7 on 2018-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0004_merge_20180905_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultExporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('path', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='defaultexporter',
            unique_together={('job', 'port')},
        ),
    ]
