# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import promgen.models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0005_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='annotations',
            field=models.TextField(validators=[promgen.models.validate_json_or_empty]),
        ),
        migrations.AlterField(
            model_name='rule',
            name='labels',
            field=models.TextField(validators=[promgen.models.validate_json_or_empty]),
        ),
    ]
