# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0007_auto_20161020_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promgen.Farm'),
        ),
    ]
