# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0008_auto_20161020_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='password',
            field=models.BooleanField(default=False),
        ),
    ]
