# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0009_auto_20161021_0640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
