# Generated by Django 2.2.4 on 2019-10-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("promgen", "0010_app_label_migration")]

    operations = [
        migrations.AddField(
            model_name="host", name="enabled", field=models.BooleanField(default=True)
        )
    ]
