# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0011_auto_20161025_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exporter',
            options={'ordering': ['job']},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
    ]
