# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0012_auto_20161027_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='clause',
            field=models.TextField(),
        ),
    ]
