# Generated by Django 2.2.9 on 2020-01-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("promgen", "0012_validation_updates")]

    operations = [migrations.RenameModel("Exporter", "Job")]
