# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0013_auto_20161027_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('labels', models.CharField(max_length=128)),
                ('value', models.FloatField()),
            ],
        ),
    ]
