# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0016_auto_20161121_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exporter',
            options={'ordering': ['job', 'port']},
        ),
    ]
