# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0017_auto_20161215_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
