# Generated by Django 2.2.10 on 2020-03-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0017_alter_alertlabel_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
