# Generated by Django 3.2.9 on 2022-01-20 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0021_shard_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExporterLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promgen.exporter')),
            ],
            options={
                'unique_together': {('exporter_id', 'name')},
            },
        ),
    ]
