# Generated by Django 4.2.11 on 2024-06-28 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0022_rule_labels_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="shard",
            name="authorization",
            field=models.CharField(
                blank=True,
                help_text="HTTP Authorization header for this shard's API",
                max_length=4083,
                null=True,
            ),
        ),
    ]
