# Generated by Django 3.2.9 on 2022-01-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0022_exporterlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporterlabel',
            name='is_parameter',
            field=models.BooleanField(default=False),
        ),
    ]
