# Generated by Django 4.2.11 on 2025-02-14 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promgen", "0023_shard_authorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w][- \\w]+$",
                        "Unicode letters, numbers, underscores, or hyphens or spaces",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w][- \\w]+$",
                        "Unicode letters, numbers, underscores, or hyphens or spaces",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_:][a-zA-Z0-9_:]*$",
                        "Only alphanumeric characters are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w][- \\w]+$",
                        "Unicode letters, numbers, underscores, or hyphens or spaces",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shard",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w][- \\w]+$",
                        "Unicode letters, numbers, underscores, or hyphens or spaces",
                    )
                ],
            ),
        ),
    ]
