# Generated by Django 3.2.9 on 2022-01-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0023_exporterlabel_is_parameter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exporterlabel',
            unique_together={('exporter_id', 'name', 'is_parameter')},
        ),
    ]
