# Generated by Django 4.2.11 on 2025-04-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0024_alter_farm_name_alter_project_name_alter_rule_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.JSONField(default=dict)),
            ],
        ),
    ]
