# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0024_auto_20170220_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleannotation',
            name='value',
            field=models.TextField(),
        ),
    ]
