# Generated by Django 4.2.11 on 2025-02-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promgen", "0024_alter_farm_name_alter_project_name_alter_rule_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
