# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0024_auto_20170220_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='shard',
            name='url',
            field=models.URLField(default='http://prometheus.example.com', max_length=256),
            preserve_default=False,
        ),
    ]
