# Generated by Django 4.2.11 on 2025-05-27 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0025_farm_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"permissions": [("process_alert", "Can process alerts")]},
        ),
    ]
