# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0026_auto_20170315_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prometheus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('shard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promgen.Shard')),
            ],
            options={
                'ordering': ['shard', 'host'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='prometheus',
            unique_together=set([('host', 'port')]),
        ),
    ]
