# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 01:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0027_prometheus_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['project__service', 'project', 'url']},
        ),
    ]
