# Generated by Django 4.2.11 on 2025-06-05 01:16

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_permissions(apps, schema_editor):
    # Get the models
    Farm = apps.get_model("promgen", "Farm")
    Project = apps.get_model("promgen", "Project")
    Service = apps.get_model("promgen", "Service")

    # Define the permissions to be created
    permissions = [
        (Farm, [("farm_admin", "Admin"), ("farm_editor", "Editor"), ("farm_viewer", "Viewer")]),
        (
            Project,
            [
                ("project_admin", "Admin"),
                ("project_editor", "Editor"),
                ("project_viewer", "Viewer"),
            ],
        ),
        (
            Service,
            [
                ("service_admin", "Admin"),
                ("service_editor", "Editor"),
                ("service_viewer", "Viewer"),
            ],
        ),
    ]

    # Create the permissions
    for model, perms in permissions:
        content_type = ContentType.objects.get_for_model(model)
        for codename, name in perms:
            Permission.objects.get_or_create(
                content_type=content_type, codename=codename, defaults={"name": name}
            )


def reverse_code(apps, schema_editor):
    # Write reverse migration code if necessary
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0027_alter_farm_owner_alter_project_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("farm_admin", "Admin"),
                    ("farm_editor", "Editor"),
                    ("farm_viewer", "Viewer"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("project_admin", "Admin"),
                    ("project_editor", "Editor"),
                    ("project_viewer", "Viewer"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("service_admin", "Admin"),
                    ("service_editor", "Editor"),
                    ("service_viewer", "Viewer"),
                ],
            },
        ),
        migrations.RunPython(create_permissions, reverse_code=reverse_code),
    ]
