# Generated by Django 4.2.11 on 2025-06-05 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0027_alter_farm_owner_alter_project_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("farm_admin", "Admin"),
                    ("farm_editor", "Editor"),
                    ("farm_viewer", "Viewer"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("project_admin", "Admin"),
                    ("project_editor", "Editor"),
                    ("project_viewer", "Viewer"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("service_admin", "Admin"),
                    ("service_editor", "Editor"),
                    ("service_viewer", "Viewer"),
                ],
            },
        ),
    ]
