# Generated by Django 4.2.11 on 2025-06-10 04:21

from django.db import migrations
from guardian.shortcuts import assign_perm

from promgen import models


def assign_admin_perm_to_owners(apps, schema_editor):
    for farm in models.Farm.objects.all():
        owner = farm.owner
        assign_perm("farm_admin", owner, farm)

    for service in models.Service.objects.all():
        owner = service.owner
        assign_perm("service_admin", owner, service)

    for project in models.Project.objects.all():
        owner = project.owner
        assign_perm("project_admin", owner, project)


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0028_alter_farm_options_alter_project_options_and_more"),
    ]

    operations = [migrations.RunPython(assign_admin_perm_to_owners)]
