# Generated by Django 4.2.11 on 2025-06-05 01:18

from django.db import migrations


def remove_group(apps, schema_editor):
    # Get the Default group
    # Note: The group name is hardcoded as "Default" in the original Promgen.
    # If the name is different in your application, you should change it
    # according to the value used in settings.PROMGEN_DEFAULT_GROUP.
    default_group = apps.get_model("auth", "Group").objects.filter(name="Default").first()

    if default_group:
        default_group.user_set.clear()
        default_group.permissions.clear()
        default_group.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0028_alter_farm_options_alter_project_options_and_more"),
    ]

    operations = [migrations.RunPython(remove_group)]
