# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0029_auto_20170406_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporter',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
