# Generated by Django 4.2.11 on 2025-08-12 13:29
import json

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def extract_data_and_populate_parent_object(apps, schema_editor):
    Farm = apps.get_model("promgen", "Farm")
    Service = apps.get_model("promgen", "Service")
    Project = apps.get_model("promgen", "Project")

    CONTENT_TYPES = {
        "project": ContentType.objects.get_for_model(Project),
        "service": ContentType.objects.get_for_model(Service),
        "farm": ContentType.objects.get_for_model(Farm),
    }

    Audit = apps.get_model("promgen", "Audit")
    for log in Audit.objects.all():
        if log.parent_content_type_id and log.parent_object_id:
            continue
        data = json.loads(log.data)

        if "content_type" in data and "object_id" in data:
            log.parent_content_type_id = data["content_type"]
            log.parent_object_id = data["object_id"]
            log.save()
        else:
            for key in CONTENT_TYPES:
                if key in data:
                    log.parent_content_type_id = CONTENT_TYPES.get(key).id
                    log.parent_object_id = data[key]
                    log.save()
                    break


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0029_migrate_owners_to_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="parent_content_type_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="audit",
            name="parent_object_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["parent_content_type_id", "parent_object_id"],
                name="promgen_aud_parent__4cbb33_idx",
            ),
        ),
        migrations.RunPython(extract_data_and_populate_parent_object),
    ]
