# Generated by Django 4.2.11 on 2025-06-10 04:21

from django.db import migrations
from guardian.shortcuts import assign_perm

from promgen import models


def assign_admin_perm_to_owners(apps, schema_editor):
    for farm in models.Farm.objects.all():
        owner = farm.owner
        if not owner.has_perm("farm_admin", farm):
            assign_perm("farm_admin", owner, farm)

    for service in models.Service.objects.all():
        owner = service.owner
        if not owner.has_perm("service_admin", service):
            assign_perm("service_admin", owner, service)

    for project in models.Project.objects.all():
        owner = project.owner
        if not owner.has_perm("service_admin", project):
            assign_perm("service_admin", owner, project)


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0029_remove_default_group"),
    ]

    operations = [migrations.RunPython(assign_admin_perm_to_owners)]
