# Generated by Django 4.2.11 on 2025-08-20 08:20

import django
from django.contrib.auth.models import Permission
from django.db import migrations

def create_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")

    content_type = ContentType.objects.get_for_model(Group)
    perms = [("group_admin", "Admin"), ("group_member", "Member")]
    for codename, name in perms:
        Permission.objects.get_or_create(
            content_type=content_type, codename=codename, defaults={"name": name}
        )


def reverse_code(apps, schema_editor):
    # Write reverse migration code if necessary
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0030_audit_parent_content_type_id_audit_parent_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RunPython(create_permissions, reverse_code=reverse_code),
    ]
