# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0031_sender_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
