# Generated by Django 4.2.11 on 2025-09-12 02:05
from django.contrib.auth.models import Permission
from django.db import migrations
from guardian.models import UserObjectPermission, GroupObjectPermission


def remove_farm_perms(apps, schema_editor):
    farm_perms = Permission.objects.filter(
        codename__in=["farm_admin", "farm_editor", "farm_viewer"]
    )
    UserObjectPermission.objects.filter(permission__in=farm_perms).delete()
    GroupObjectPermission.objects.filter(permission__in=farm_perms).delete()
    farm_perms.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0032_alter_farm_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={"ordering": ["name"]},
        ),
        migrations.RunPython(remove_farm_perms),
    ]
