# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0032_audit_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='old',
            field=models.TextField(blank=True),
        ),
    ]
