# Generated by Django 4.2.11 on 2025-09-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0033_remove_farm_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='owner',
        ),
    ]
