# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0033_diff_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prometheus',
            options={'ordering': ['shard', 'host'], 'verbose_name_plural': 'prometheis'},
        ),
    ]
