# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0034_auto_20170622_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='promgen.Rule'),
        ),
    ]
