# Generated by Django 4.2.11 on 2025-09-24 10:12

from django.db import migrations


def remove_orphan_farms(apps, schema_editor):
    Farm = apps.get_model("promgen", "Farm")
    Project = apps.get_model("promgen", "Project")
    farms_linked_to_projects = set(Project.objects.values_list("farm_id", flat=True))
    for farm in Farm.objects.exclude(id__in=farms_linked_to_projects):
        farm.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0034_remove_farm_owner"),
    ]

    operations = [
        migrations.RunPython(remove_orphan_farms),
    ]
