# Generated by Django 4.2.11 on 2025-09-23 02:34

from django.db import migrations, models
import django.db.models.deletion


def populate_farm_project(apps, schema_editor):
    for project in apps.get_model("promgen", "Project").objects.all():
        farm = project.farm
        if farm:
            farm.project = project
            farm.save()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0035_remove_orphan_farms"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="promgen.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="promgen.farm",
            ),
        ),
        migrations.RunPython(populate_farm_project),
    ]
