# Generated by Django 4.2.11 on 2025-10-27 10:15
from django.contrib.auth.models import Permission, User
from django.db import migrations
from guardian.models import UserObjectPermission
from guardian.shortcuts import assign_perm, get_perms, remove_perm


def reassign_owner_and_admin_perm_for_projects(apps, schema_editor):
    Project = apps.get_model("promgen", "Project")
    for project in Project.objects.all():
        project_owner = User.objects.get(id=project.owner.id)
        if not UserObjectPermission.objects.filter(
            user=project_owner,
            object_pk=project.pk,
            permission=Permission.objects.get(codename="project_admin"),
        ).exists():
            new_owner = User.objects.get(id=project.service.owner.id)
            permissions = get_perms(new_owner, project)
            for perm in permissions:
                remove_perm(perm, new_owner, project)
            assign_perm("project_admin", new_owner, project)

            project.owner = project.service.owner
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0037_remove_project_farm_alter_farm_project"),
    ]

    operations = [
        migrations.RunPython(reassign_owner_and_admin_perm_for_projects),
    ]
