# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promgen', '0037_shard_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
