# Generated by Django 4.2.11 on 2025-11-04 08:58
from django.contrib.auth.models import Permission, User
from django.db import migrations
from guardian.models import UserObjectPermission
from guardian.shortcuts import assign_perm, get_perms, remove_perm


def migrate_sender(apps, schema_editor):
    """
    Migrate Sender objects that use the User notification
    to use the User's primary key instead of username for value.
    """

    Sender = apps.get_model("promgen", "Sender")
    for sender in Sender.objects.filter(sender="promgen.notification.user"):
        try:
            user = User.objects.get(username=sender.value)
            sender.value = str(user.pk)
            sender.save()
        except User.DoesNotExist:
            # If the user does not exist, it means the association is lost forever.
            # So the sender is redundant and we can just delete it.
            sender.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0038_reassign_owner_and_admin_perm_for_projects"),
    ]

    operations = [
        migrations.RunPython(migrate_sender),
    ]
