# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import promgen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0038_audit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='clause',
            field=models.TextField(help_text='Prometheus query'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='duration',
            field=models.CharField(help_text='Duration field with postfix. Example 30s, 5m, 1d', max_length=128, validators=[promgen.validators.prometheusduration]),
        ),
    ]
