# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 06:53
from __future__ import unicode_literals

from django.db import migrations


def rename_to_default(apps, schema_editor):
    Farm = apps.get_model('promgen', 'Farm')
    Farm.objects.filter(source='promgen').update(source='default')


def rename_to_promgen(apps, schema_editor):
    Farm = apps.get_model('promgen', 'Farm')
    Farm.objects.filter(source='default').update(source='promgen')


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0039_auto_20170725_0257'),
    ]

    operations = [
        migrations.RunPython(rename_to_promgen, rename_to_default, elidable=True),
    ]
