# Generated by Django 4.2.26 on 2026-01-05 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0039_migrate_user_type_sender_to_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(
                max_length=256,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
    ]
