# Generated by Django 4.2.26 on 2026-01-21 02:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0040_alter_url_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z_:][a-zA-Z0-9_:]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True)),
                ("labels", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="MetricSample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("labels", models.CharField(help_text="List of label values", max_length=512)),
                ("data", models.JSONField(default=dict)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="promgen.metric"
                    ),
                ),
            ],
            options={
                "unique_together": {("metric", "labels")},
            },
        ),
    ]
