# Generated by Django 4.2.26 on 2026-01-20 07:19

from django.db import migrations


def add_metrics(apps, schema_editor):
    Metric = apps.get_model("promgen", "Metric")
    Metric.objects.get_or_create(
        name="promgen_alert_notifications_total",
        type="counter",
        description="Total number of alert notifications sent",
        labels=["sender_type", "hostname"],
    )
    Metric.objects.get_or_create(
        name="promgen_alert_notifications_error_total",
        type="counter",
        description="Total number of alert notifications sent in error",
        labels=["sender_type", "error_type", "hostname"],
    )
    Metric.objects.get_or_create(
        name="promgen_alert_notification_duration_seconds",
        type="histogram",
        description="Histogram of alert notification durations in seconds",
        labels=["sender_type", "status", "hostname"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0041_metric_metricsample"),
    ]

    operations = [
        migrations.RunPython(add_metrics),
    ]
