# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promgen', '0042_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
