# Generated by Django 4.2.11 on 2025-08-14 08:34

from django.db import migrations


def remove_group(apps, schema_editor):
    """
    Remove the Default group and its associated permissions.

    Remove the group name which is hardcoded as "Default" in the original Promgen.
    If the name is different in your application, you should change it
    according to the value used in settings.PROMGEN_DEFAULT_GROUP.
    """
    default_group = apps.get_model("auth", "Group").objects.filter(name="Default").first()

    if default_group:
        default_group.user_set.clear()
        default_group.permissions.clear()
        default_group.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0042_alert-notification-instrumentation"),
    ]

    operations = [migrations.RunPython(remove_group)]
