# Generated by Django 4.2.26 on 2026-03-06 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0043_remove_default_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricsample",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="promgen.metric",
            ),
        ),
    ]
