# Generated by Django 4.2.26 on 2026-03-06 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0044_alter_metricsample_metric"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="probe",
            options={"ordering": ["module"]},
        ),
    ]
