# Generated by Django 4.2.26 on 2026-05-13 12:00

from django.db import migrations


def add_metrics(apps, schema_editor):
    Metric = apps.get_model("promgen", "Metric")
    Metric.objects.get_or_create(
        name="promgen_requests_total",
        type="counter",
        description="Total number of requests processed",
        labels=["endpoint", "hostname", "method", "status_code"],
    )
    Metric.objects.get_or_create(
        name="promgen_requests_duration_seconds",
        type="histogram",
        description="Histogram of request durations in seconds",
        labels=["endpoint", "hostname", "method"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0045_alter_probe_options"),
    ]

    operations = [
        migrations.RunPython(add_metrics),
    ]
