# Generated by Django 4.2.26 on 2026-08-12 14:40


from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from django.db import migrations

from promgen.notification.email import NotificationEmail


def remove_invalid_email_notifiers(apps, schema_editor):
    Sender = apps.get_model("promgen", "Sender")
    validate_email = EmailValidator()

    invalid_notifiers = []
    for notifier in Sender.objects.filter(sender=NotificationEmail.__module__):
        try:
            validate_email(notifier.value)
        except ValidationError:
            invalid_notifiers.append(notifier.pk)

    if invalid_notifiers:
        Sender.objects.filter(pk__in=invalid_notifiers).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0046_requests_instrumentation"),
    ]

    operations = [
        migrations.RunPython(remove_invalid_email_notifiers),
    ]
