# Generated by Django 4.2.26 on 2026-08-19 14:30

from django.db import migrations


def populate_rule_content_object_labels(apps, schema_editor):
    Rule = apps.get_model("promgen", "Rule")

    rules_to_update = []
    for rule in Rule.objects.all().select_related("content_type"):
        model_class = apps.get_model("promgen", rule.content_type.model)
        obj = model_class.objects.get(pk=rule.object_id)

        updated = False

        if "site" == rule.content_type.model:
            if rule.labels.pop("service", None) is not None:
                updated = True
            if rule.labels.pop("project", None) is not None:
                updated = True
        elif "service" == rule.content_type.model:
            if rule.labels.get("service") != obj.name:
                rule.labels["service"] = obj.name
                updated = True
            if rule.labels.pop("project", None) is not None:
                updated = True
        elif "project" == rule.content_type.model:
            if rule.labels.get("service") != obj.service.name:
                rule.labels["service"] = obj.service.name
                updated = True
            if rule.labels.get("project") != obj.name:
                rule.labels["project"] = obj.name
                updated = True

        if updated:
            rules_to_update.append(rule)

    if rules_to_update:
        Rule.objects.bulk_update(rules_to_update, ["labels"])


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0047_remove_invalid_email_notifiers"),
    ]

    operations = [
        migrations.RunPython(populate_rule_content_object_labels),
    ]
