# Generated by Django 4.2.26 on 2026-09-14 03:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import promgen.validators


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0050_migrate_existing_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label_name",
                    models.CharField(
                        max_length=128,
                        validators=[
                            promgen.validators.custom_label_name,
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Is this label required for its model?"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "db_table": "promgen_custom_label",
                "unique_together": {("label_name", "model")},
            },
        ),
        migrations.CreateModel(
            name="CustomLabelInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\w][- \\w]+$",
                                "Unicode letters, numbers, underscores, or hyphens or spaces",
                            )
                        ],
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "custom_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="promgen.customlabel"
                    ),
                ),
            ],
            options={
                "db_table": "promgen_custom_label_instance",
                "unique_together": {("custom_label", "content_type", "object_id")},
            },
        ),
    ]
