# Generated by Django 4.2.26 on 2026-09-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0052_alter_customlabel_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customlabel",
            name="model",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "promgen"), ("model", "service")),
                    models.Q(("app_label", "promgen"), ("model", "project")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="customlabelinstance",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "promgen"), ("model", "service")),
                    models.Q(("app_label", "promgen"), ("model", "project")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
