# Generated by Django 4.2.26 on 2026-09-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promgen", "0053_alter_customlabel_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlabel",
            name="is_added_to_metric",
            field=models.BooleanField(
                default=True, help_text="Is this label added to metrics when scrapping targets?"
            ),
        ),
    ]
